### ISSUE TITLE
雪宝不显示课程

### ISSUE THREAD

**Issue by brijagstu7** [looyeagee/looyeagee.github.io#1]
雪宝登陆之后页面是空的，不显示课程。

**Comment by looyeagee** [comment]
您好,可能是新的学期没有课程.您可以登录官方学宝看一下是否有课程,如果官方有我这里没有,再向我反馈.

**Comment by brijagstu7** [comment]
> 您好,可能是新的学期没有课程.您可以登录官方学宝看一下是否有课程,如果官方有我这里没有,再向我反馈.

在学宝客户端登录不显示课程，但是可以在右下角调整学期，然后就可以有课程。而网页版雪宝没有这样的操作。

**Comment by looyeagee** [comment]
等我找到工作后,我再考虑维护😁.已经将这个需求记录.谢谢~

**Comment by looyeagee** [comment]
啊啦啦，更新啦，可以选学期啦。
